/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JUnit.Testing;
import org.junit.*;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import static org.junit.Assert.*;

import org.junit.Assert;

public class MoodAnalyserTest {
	public static MoodAnalyser moodAnalyser=null;
	@Test
	public void initialize() throws userexception
	{
		try{
			ExpectedException ex=ExpectedException.none();
			ex.expect(userexception.class);
			String mood=AnalyseMood(null);
		}
		catch(userexception e)
		{
			System.out.println(e.exceptiontype);
			Assert.assertEquals(userexception.ExceptionType.ENTERED_NULL, e.exceptiontype);
		}
		//moodAnalyser=new MoodAnalyser();
	}
	/*@Test
    public void givenMessage_whenSad_shouldreturnSad()
    {
    	String mood=moodAnalyser.analyseMood("This is a Sad message");
    	Assert.assertEquals("SAD", mood);
    }
	@Test
    public void givenMessage_whenHappy_shouldreturnHappy()
	{
    	String mood=moodAnalyser.analyseMood("This is a Happy message");
    	Assert.assertEquals("HAPPY", mood);
	}**/
	public String AnalyseMood(String st) throws userexception
	{
		try{
			if(st.contains("sad"))
				return "SAD";
			else
				return "HAPPY";
		}
			catch(NullPointerException e)
		{
				Assert.assertEquals(userexception.ExceptionType.ENTERED_NULL, e);
		}
		return st;
	}
}
